accent = "#8f7ae6"
cursor = "#ffcfb8"
foreground = "#ffcfb8"
background = "#12081f"
selection_foreground = "#12081f"
selection_background = "#ffcfb8"

color0 = "#12081f"
color1 = "#ee6b73"
color2 = "#98aca0"
color3 = "#efc15e"
color4 = "#8f7ae6"
color5 = "#cd9fe8"
color6 = "#9fcfe0"
color7 = "#f49a7a"
color8 = "#7a68be"
color9 = "#ffb29c"
color10 = "#cad4cd"
color11 = "#f7dd9d"
color12 = "#cfc8ff"
color13 = "#eddcff"
color14 = "#dcecf4"
color15 = "#ffcfb8"
